fix: npx 安装 conventional-changelog-cli 失败
npm WARN exec The following package was not found and will be installed: conventional-changelog-cli
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Error: Unable to process file command 'env' successfully.
Error: Invalid environment variable format '### Bug Fixes'